# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :export_ipa_1 do
    gym(
      export_method: "development",     # 使用免費帳號建議選擇 "development"
      scheme: "Test-Demo",              # 替換為您的 scheme 名稱
      configuration: "Debug",           # 免費帳號只能用 Debug 配置
      output_directory: "./build",
      output_name: "Test-Demo.ipa",
      export_options: {
        provisioningProfiles: {
          "com.leyee.Test-Demo" => "220005d7-ce79-491d-9b9d-cf5fa6c544a3"
        }
      }
    )
  end

  lane :export_ipa_2 do
    gym(
      export_method: "development",                # 可以改為 "development" 因為您是免費憑證
      export_xcargs: "-allowProvisioningUpdates",
      scheme: "Test-Demo",                         # 替換為您的 scheme 名稱
      output_directory: "./build",                 # IPA 檔案存放位置
      output_name: "Test-Demo.ipa",                # 輸出檔名
      build_path: "./build"                        # 指定構建路徑
    )
  end

end
